name: Rust
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: ['main']
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.4.1
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Build WASM package
        run: cd game_of_life/ && chmod +x build-wasm.sh && ./build-wasm.sh
      - name: Build static site
        run: cd game_of_life_web/www/ && pnpm run build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Branche cible (ne pas changer)
          folder: game_of_life_web/www/dist # Dossier généré à partir de main
          clean: true # Nettoie les anciens fichiers
          single-commit: true # Évite les branches intermédiaires
          force: true # Force le déploiement même s'il n'y a pas de changement détect

